import { CatalogWidget } from '@/widgets/catalog'
import { Metadata } from 'next'

import { findProduct, ISearchParamsTypes } from '@/features/filters/helpers/findProducts';

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export async function CatalogPage({searchParams}: {searchParams: ISearchParamsTypes}) {

  const products = await findProduct(searchParams)
  //  const products = await productApi.getProducts('products?category=81&attribute=pa_ml&attribute_term=186&attribute=pa_noty&attribute_term=165')

  if(!products) return("Products not found!")

  return <>
      <CatalogWidget items={products}  />
    </>;
}
