import { CatalogWidget } from '@/widgets/catalog'
import { Metadata } from 'next'

import {productApi} from "@/shared/api"

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export async function CatalogPage() {
  //const products = await productApi.getProducts()

   const products = await productApi.getProducts('products?category=81&attribute=pa_ml&attribute_term=186&attribute=pa_noty&attribute_term=165')

   const attributes = await productApi.getProductsAttributes()

  if(!products) return("Products not found!")

  return <>
      <CatalogWidget items={products} attributes={attributes} />
    </>;
}
