import { CatalogWidget } from '@/widgets/catalog'
import { Metadata } from 'next'

import {productApi} from "@/shared/api"

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export async function CatalogPage() {

  const products = await productApi.getProducts()

  if(!products) return("Products not found!")

  return <>
    <CatalogWidget items={products} />
    </>;
}
