import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export function DeeperPage() {
  return <div>This page is catalog !</div>;
}
