import {PersonData} from "@/features/formCheckout/ui/personData"
import {RecipientData} from "@/features/formCheckout/ui/recipientData"
import {CongratulationWords} from "@/features/formCheckout/ui/CongratulationWords"
import {Delivery} from "@/features/formCheckout/ui/delivery"
import {Message} from "@/features/formCheckout/ui/message"
import {Payment} from "@/features/formCheckout/ui/payment"
import {Packing} from "@/features/formCheckout/ui/packing"